cache:
  npm: false
language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUILabs
  - REPO_NAME=facet-filter-sort
  - SAUCE_USERNAME: Desire2Learn
  # GITHUB_RELEASE_TOKEN
  - secure: h6WVsEKE/wESqOx6rTfGPMy19T18frG1C6LlV5z6cVdQ40fFIDJK/zaj2FyBojSOra2WcyNeOHTEVh7IqOwdC0/bjyGfFKaC7mXafFJtyOwNmAGV8egGflIMNBvauukEddBWIMCGfm9ETDiJULmHBuL9Qa5iBTVmnqzAiMI9xe4MhjNcS5Z8+WAYZXPZdjEI6zpszq5NCQ46qx2qLAG+Oqcz78BZEUUFmzTThT9zKAKde+gxoKCvq7zaXFKOiFb1wDJELVptx36RcQUpoEgqZ07ZCZD0Pnk0mkX9Gz7fYyJqlPJtq1JUyOI4sAumCDy5MjPuaIJ3MFOFI2ICrhPj9QPvuYX8SpGUMZ7i7XWG5WtECt2C8JclZm4Opj9gm+prazTM5zxDfZ5qHagMn10EoRL7cYr96dbTvmcTSovj7ac0oklO5S7BZz5DevGXxurlY59jrLims9JvXonRLd1bCjzRcyw1eTxFgSTgY6/mrfL+YxXVT24jCh2htTE8x8z/PJkFIhL0cs0BWz/R9jBLSBdEmYAckMN+aJfLrp8P1PP7I/DM2x2wlktRLlRCu5XftjxR3FaGFgdViztVYUoLysFtldtzgA5eZWA1qwsBk36qZo90feB7sgxEWNIheUm6i+hTdLy98lXRcRNtyYl/qb3BgqKiNbq9aU7hwOTvOX0=
  # SAUCE_ACCESS_KEY
  - secure: gRXys8GcjNAphNSBPNheIVHuZy9PSfxuD5x1f5sghJlM0i+lvZdOJ5tLj5fesAsYapi4JjkU7pKNdkn+JRQfy+eKT3s8dboV3FXRQv9AB7QvsBHomjfXFhNrvKxKZA0H6a/gHj8jjEA3I/Yqxsk9cHecyTjb96wPJH4SsqUNO0+BqrGg7sAlua41ZtdjCexoOKzpGOYPbssj6sv0B3D2ix/uJqgX8HOucVmtRo/qj+lYtsa1fdTNHEb4ubhsFZ4M6NetvYtnNP1MG+uHoeifrR/4vcYaEKVdvLcNgpllnXbmpVn9MTPtxpqKKCi/0JuyTqbedwC2Hf9b9BUxCdp8ISNJnpsVS9vpq14p0mOfNdQhgFG0sen8KmDhzid1kkWlMtTb9ITMDjYdeaVADP1Ecf7Jl2CGsiMOvj/yCuPBPaCZWgQrPO6Z1ApSrM6YAjJp+2lxCyolu8ZiV5ZH+0K+Q+eDGOMCyFbWdoQvDooNt+oj8X7td0xJ3WcTlLRJjPJUGsbfI4HCcIcpFTPIhesc7TEtPXCwpMv+2CdS5Smnt/68E3I7LajqyeQ7PGVmzqc1FaTkYaeU7ZBGGOc5cAsAZsMobY0W4krJv9VNYn2UbZ6FqiMEO3p5MgmLBuF2FVzJG+idhIDwzvxBBUEtgZEVaHmdacqlTOtLDFUh1JlVBSY=
