cache:
  npm: false
language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUILabs
  - REPO_NAME=facet-filter-sort
  - SAUCE_USERNAME: Desire2Learn
  # GITHUB_RELEASE_TOKEN
  - secure: lxZQYO0IDx37rzBBEmwsWgEdCREFrgzlAy0aAJLeHtqWHKvcPxoxNtYYxpAkq1AvIK8Dci4idGnF/qETHmoYA+bpBuxJfwsHO0dv3og3jGxzRHmopATvjNBJDYL0fb6NQQd7iqNvrxjJJN7h/fxz7zQ+hakTx4O+9zd8BhoCE2yc3+YLzvfRBO12TySxhN3TiMI7x481YZa1htuJ85Y5bFwy04ilTjvC7/sjD7jolNJhXbbZdfu5c+9OVhXvvFLv/ZNHR4GQ+tjeVtpOXP4+HYthS5ichm5Wa0+Cha4zC/2bDp261i2l+bSTtQxPBiszpRQrIjsh/JfYp6qcTYT+Y0kWDFEAIPiWC6QAbJZG4BNdtmXTgfRBUCg80YxKIW1X/nqvIX0QDAUMUj1rrq9CshhIkgSFZqomj4aRP5CmPegKKYUus5mfJRsq2kMHzBTzwMj1l2+TI1e7C9ewBg3Tw+Icm7jZ4wYH7UVc0Wzii0iB3akfJoWuNkv3T8d4slS2YoaShWA3r5+lQafFBRKmwj7qdIF3OBv6zv55crtVqQX72PwSgO3BhZSf6REJJgMPeeZT17jL2WB0AR3Rli4WKKIC/2zGGe9RKgmRrUN9nGPZn4RUVlSy7PUb0BKA/gov0tszV+XMOtarasHn5e2ZLeUklpizMnP2OsITMdWytnY=
  # SAUCE_ACCESS_KEY
  - secure: gRXys8GcjNAphNSBPNheIVHuZy9PSfxuD5x1f5sghJlM0i+lvZdOJ5tLj5fesAsYapi4JjkU7pKNdkn+JRQfy+eKT3s8dboV3FXRQv9AB7QvsBHomjfXFhNrvKxKZA0H6a/gHj8jjEA3I/Yqxsk9cHecyTjb96wPJH4SsqUNO0+BqrGg7sAlua41ZtdjCexoOKzpGOYPbssj6sv0B3D2ix/uJqgX8HOucVmtRo/qj+lYtsa1fdTNHEb4ubhsFZ4M6NetvYtnNP1MG+uHoeifrR/4vcYaEKVdvLcNgpllnXbmpVn9MTPtxpqKKCi/0JuyTqbedwC2Hf9b9BUxCdp8ISNJnpsVS9vpq14p0mOfNdQhgFG0sen8KmDhzid1kkWlMtTb9ITMDjYdeaVADP1Ecf7Jl2CGsiMOvj/yCuPBPaCZWgQrPO6Z1ApSrM6YAjJp+2lxCyolu8ZiV5ZH+0K+Q+eDGOMCyFbWdoQvDooNt+oj8X7td0xJ3WcTlLRJjPJUGsbfI4HCcIcpFTPIhesc7TEtPXCwpMv+2CdS5Smnt/68E3I7LajqyeQ7PGVmzqc1FaTkYaeU7ZBGGOc5cAsAZsMobY0W4krJv9VNYn2UbZ6FqiMEO3p5MgmLBuF2FVzJG+idhIDwzvxBBUEtgZEVaHmdacqlTOtLDFUh1JlVBSY=
